"""Two-block group-algebra (2BGA) codes for ARBITRARY finite groups.

Generalizes ``bb.py`` (the abelian G = Z_l x Z_m special case) to any finite
group, including non-abelian ones -- the design space where the record encoding
efficiencies live (non-abelian 2BGA can even reach odd k, impossible for
abelian BB).

Construction (Lin & Pryadko, arXiv:2306.16400), left-right two-block form:
  G a finite group, |G| = N. Pick supports a, b subset of G.
  L(g) = left-regular-rep permutation matrix:  L(g) e_h = e_{g h}
  R(g) = right-regular-rep permutation matrix: R(g) e_h = e_{h g}
  L(a) = sum_{g in a} L(g),  R(b) = sum_{g in b} R(g)
  H_X = [ L(a) | R(b) ],  H_Z = [ R(b)^T | L(a)^T ],   n = 2N

CSS commutation is AUTOMATIC: left and right multiplications commute, so
H_X H_Z^T = L(a)R(b) + R(b)L(a) = 0 (mod 2) for any a, b.

A group is given as a multiplication table ``mul`` (N x N int array,
``mul[i, j]`` = index of g_i * g_j) with the identity at index 0. Build one
from permutation generators with ``perm_group``, or use the helpers
(``cyclic_product``, ``dihedral``, ``metacyclic``, ``sym``, ``alt``).
"""
import numpy as np


# ----------------------------------------------------------------------
#  Group construction
# ----------------------------------------------------------------------
def _compose(p, q):
    """(p . q)(i) = p[q[i]]  -- apply q then p."""
    return tuple(p[q[i]] for i in range(len(q)))


def perm_group(gens, degree):
    """Group generated by permutations ``gens`` (tuples on 0..degree-1) via BFS
    closure. Returns ``(mul, elems)``: the N x N Cayley table (identity at index
    0) and the element list."""
    ident = tuple(range(degree))
    elems = [ident]
    index = {ident: 0}
    frontier = [ident]
    while frontier:
        nxt = []
        for e in frontier:
            for g in gens:
                h = _compose(e, g)
                if h not in index:
                    index[h] = len(elems)
                    elems.append(h)
                    nxt.append(h)
        frontier = nxt
    N = len(elems)
    mul = np.zeros((N, N), dtype=np.int64)
    for i, ei in enumerate(elems):
        for j, ej in enumerate(elems):
            mul[i, j] = index[_compose(ei, ej)]
    return mul, elems


def cyclic_product(*orders):
    """Abelian group Z_{o1} x ... x Z_{ok} as a Cayley table. Identity at index
    0. (On Z_l x Z_m this reproduces the ``bb.py`` torus family.)"""
    from itertools import product
    tuples = list(product(*[range(o) for o in orders]))
    index = {t: i for i, t in enumerate(tuples)}
    N = len(tuples)
    mul = np.zeros((N, N), dtype=np.int64)
    for i, ti in enumerate(tuples):
        for j, tj in enumerate(tuples):
            s = tuple((a + b) % o for a, b, o in zip(ti, tj, orders))
            mul[i, j] = index[s]
    return mul, tuples


def direct_product(mulA, mulB):
    """Cayley table of A x B (identity stays at index 0 if both inputs do)."""
    a, b = mulA.shape[0], mulB.shape[0]
    N = a * b
    mul = np.zeros((N, N), dtype=np.int64)
    for i in range(a):
        for j in range(b):
            for ii in range(a):
                for jj in range(b):
                    mul[i * b + j, ii * b + jj] = mulA[i, ii] * b + mulB[j, jj]
    return mul, [(i, j) for i in range(a) for j in range(b)]


def metacyclic(n, k, r):
    """Semidirect product C_n |x C_k with action j: i -> r^j * i (mod n).
    Requires r^k == 1 (mod n). Elements (i, j) at index i*k + j; identity
    (0, 0) = 0. Dihedral D_n = metacyclic(n, 2, n-1). A rich source of
    structured non-abelian (solvable) groups."""
    assert pow(r, k, n) == 1, f"r^k != 1 mod n: {r}^{k} mod {n} = {pow(r, k, n)}"
    rp = [pow(r, j, n) for j in range(k)]
    idx = lambda i, j: (i % n) * k + (j % k)
    N = n * k
    mul = np.zeros((N, N), dtype=np.int64)
    for i in range(n):
        for j in range(k):
            for ii in range(n):
                for jj in range(k):
                    mul[idx(i, j), idx(ii, jj)] = idx(i + rp[j] * ii, j + jj)
    return mul, [(i, j) for i in range(n) for j in range(k)]


def dihedral(n):
    """Dihedral group D_n of order 2n (rotation r, reflection s) on n points."""
    r = tuple((i + 1) % n for i in range(n))
    s = tuple((-i) % n for i in range(n))
    return perm_group([r, s], n)


def sym(n):
    """Symmetric group S_n (order n!)."""
    cyc = tuple([1, 0] + list(range(2, n)))             # transposition (0 1)
    rot = tuple([(i + 1) % n for i in range(n)])        # n-cycle
    return perm_group([cyc, rot], n)


def alt(n):
    """Alternating group A_n (order n!/2)."""
    three = tuple([1, 2, 0] + list(range(3, n)))                 # (0 1 2)
    if n % 2 == 1:
        longc = tuple([(i + 1) % n for i in range(n)])           # n-cycle (even)
    else:
        longc = tuple([0] + [1 + (i + 1) % (n - 1) for i in range(n - 1)])
    return perm_group([three, longc], n)


# ----------------------------------------------------------------------
#  Left / right regular representations and the 2BGA code
# ----------------------------------------------------------------------
def L_rep(mul, g):
    """Left-mult permutation matrix L(g): L(g)[g*h, h] = 1."""
    N = mul.shape[0]
    M = np.zeros((N, N), dtype=np.int8)
    M[mul[g, :], np.arange(N)] = 1
    return M


def R_rep(mul, g):
    """Right-mult permutation matrix R(g): R(g)[h*g, h] = 1."""
    N = mul.shape[0]
    M = np.zeros((N, N), dtype=np.int8)
    M[mul[:, g], np.arange(N)] = 1
    return M


def block(mul, elems_a, side):
    """Sum (mod 2) of regular-rep matrices over a subset of element indices.
    ``side='L'`` -> L(a) = sum L(g); ``side='R'`` -> R(b) = sum R(g)."""
    N = mul.shape[0]
    M = np.zeros((N, N), dtype=np.int8)
    rep = L_rep if side == "L" else R_rep
    for g in elems_a:
        M = (M + rep(mul, g)) % 2
    return M.astype(np.int8)


def build_2bga(mul, a, b):
    """2BGA code from Cayley table ``mul``, with ``a, b`` lists of element
    indices (the supports of a, b in F2[G]).

    Returns HX, HZ int8 arrays of shape (N, 2N). CSS guaranteed.
    """
    La = block(mul, a, "L")
    Rb = block(mul, b, "R")
    HX = np.concatenate([La, Rb], axis=1).astype(np.int8)
    HZ = np.concatenate([Rb.T, La.T], axis=1).astype(np.int8)
    return HX, HZ


if __name__ == "__main__":
    from css import verify_css, compute_k
    from surrogate import distance_rand

    # Abelian self-test: the 2BGA on Z_6 x Z_6 must reproduce the gross-code
    # PARAMETERS [[72,12,6]]. (The matrices differ from bb.py only by the
    # shift-direction convention; the code -- n, k, d -- is the same.)
    mul, tup = cyclic_product(6, 6)
    idx = {t: i for i, t in enumerate(tup)}
    a = [idx[(3, 0)], idx[(0, 1)], idx[(0, 2)]]   # x^3 + y + y^2 (left)
    b = [idx[(0, 3)], idx[(1, 0)], idx[(2, 0)]]   # y^3 + x + x^2 (right)
    HX, HZ = build_2bga(mul, a, b)
    n, k = HX.shape[1], compute_k(HX, HZ)
    d = distance_rand(HX, HZ, trials=400)
    print(f"abelian Z6xZ6 2BGA: n={n} k={k} css={verify_css(HX, HZ)} d<={d} "
          f"(reproduces gross code [[72,12,6]]: {(n, k, d) == (72, 12, 6)})")

    # Non-abelian: a regular 2BGA on A4 (order 12) yields a valid CSS code with
    # ODD k -- impossible for abelian BB. A4 = <(0 1 2), (0 1)(2 3)>.
    mul4, el4 = perm_group([(1, 2, 0, 3), (1, 0, 3, 2)], 4)
    xi, yi, e = el4.index((1, 2, 0, 3)), el4.index((1, 0, 3, 2)), 0
    inv = [el4.index(tuple(np.argsort(g))) for g in el4]

    def gm(*gs):
        r = 0
        for g in gs:
            r = int(mul4[r, g])
        return r

    a = sorted({e, xi, yi, gm(inv[xi], yi, xi)})
    b = sorted({e, xi, yi, gm(yi, xi)})
    HX, HZ = build_2bga(mul4, a, b)
    print(f"non-abelian A4 2BGA: n={HX.shape[1]} k={compute_k(HX, HZ)} "
          f"css={verify_css(HX, HZ)} d<={distance_rand(HX, HZ, trials=1500)} "
          f"(odd k is unreachable by abelian BB)")
