#!/usr/bin/env python3
"""Stage C: generate natural-layout audit candidates without changing codes/."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "research/candidates"


def bb_z9_z6() -> list[list[float]]:
    # The CSS blocks each contain 9*6 qubits. Use the construction's quotient
    # coordinates for both qubit layers; layers=2 records the bilayer.
    return [[float(q % 9), float(q // 9)] for layer in range(2) for q in range(54)]


def cpm_p13_j8() -> list[list[float]]:
    # CPM qubit index is block-column * p + lift index, as documented by the
    # submitted construction's exponent convention.
    return [[float(q % 13), float(q // 13)] for q in range(104)]


def make(source: str, target: str, coordinates: list[list[float]], layers: int | None) -> None:
    doc = json.loads((ROOT / "codes" / source).read_text())
    doc["name"] = doc["name"] + " natural-layout audit"
    doc["provenance"] = dict(doc["provenance"])

    doc["provenance"]["notes"] = (
        doc["provenance"].get("notes", "")
        + " Natural coordinates generated by research/layout_audit_sample.py; "
          "audit result is not a new code."
    )
    doc["locality"] = {"coordinates": coordinates}
    if layers is not None:
        doc["locality"]["layers"] = layers
    path = OUT / target
    path.write_text(json.dumps(doc, indent=2) + "\n")
    print(path)


if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    make("108-8-10.json", "layout-audit-108-8-10.json", bb_z9_z6(), 2)
    make("104-30-8.json", "layout-audit-104-30-8.json", cpm_p13_j8(), 1)
